sudo: false
language: node_js
node_js:
  - 6
# https://docs.travis-ci.com/user/database-setup/#PostgreSQL
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
after_success:
  - pip install --user codecov
  - codecov --file coverage/lcov.info --disable search
env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/test
    - JWT_SECRET=McAwesomeAppFactory
    - GITHUB_AUTH_REDIRECT_URL=/githubauth
