language: node_js
node_js:
  - 4
  - 6
  - 7
services:
  - redis-server
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
sudo: false
env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/test
    - JWT_SECRET=McAwesomeAppFactory
    - GITHUB_AUTH_REDIRECT_URL=/githubauth
# https://docs.travis-ci.com/user/database-setup/#PostgreSQL
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
